### ISSUE TITLE
Emoji parsing doesn't work on python compiled in wide mode

### ISSUE THREAD

**Issue by ikornaselur** [TakumiHQ/instagram-text-python#9]
# Description

Parsing for emojis doesn't seem to work on linux. Tested on Ubuntu 14.04.5 LTS. Fresh virtualenv with Python 2.7.6 and only this package installed.

Screenshot below shows the emoji parsing being tested on said linux machine (above) and my mac (below)

![image](https://cloud.githubusercontent.com/assets/3537289/17888492/c490fdfa-691a-11e6-9a66-44d03a9c6704.png)

**Comment by ikornaselur** [comment]
Seems this is related to python being compiled with UCS2 vs UCS4. It's UCS2 on my mac, while it's UCS4 on the linux box.

**Comment by steinnes** [comment]
The test is hardcoding the UCS2 string, right?  Maybe we if we read the string from a file which is unicode encoded, instead of hardcoding UCS2 (ie. `u'\U0001F525'` is a 2x 16bit unicode widechar), it would work on both platforms?  Because the unicode regexp is definitely working on Linux (our servers are Linux :-))

**Comment by steinnes** [comment]
(not an awesome solution though, would be nice to keep the test data inside tests.py and represent the unicode strings in a cross platform way, or at least detect the platform via sys.maxunicode > 2**16 and convert if necessary)

**Comment by ikornaselur** [comment]
But isn't the problem that I'm using a regex that's looking for the surrogate pairs ([see here](https://github.com/TakumiHQ/instagram-text-python/blob/50b4f7d403a84afa1b08cf3f30d1bd39fe9743bb/itp/itp.py#L34))? Doesn't it make sense that i need to have two different regular expressions based on the `sys.maxunicode`?

I've been looking into if I can generate the regular expression from TR51 standards ([like in the Emojineering Part 2 blog post](http://instagram-engineering.tumblr.com/post/118304328152/emojineering-part-2-implementing-hashtag-emoji)) for both UTF16 and UTF32.

Either that, or see if I can convert the string being parsed, before using `reg.sub()` on it, but I'm not sure that's possible?

**Comment by ikornaselur** [comment]
I'll be honest btw, this is all very foreign to me 😸  - I'm learning a lot at the moment.

**Comment by steinnes** [comment]
Initially I thought the regex would need to be changed, but if we are currently detecting emojis on Linux, with this regex, then I thought that might be avoided (mostly because unless we can automatically convert the regex data between encodings it means more maintenance overhead).

But you are right, we can also do this via ucs-2/ucs-4 detection + two regexps, but I think that would also require the test data to be in the correct (or matching) encoding.

I tried the regexp on `u'\xf0\x9f\x94\xa5'` and it didn't work, so I'm not quite sure how it's working on Linux, unless unicode is always uniformly encoded in JSON, and that's why it works on Linux -- or doesn't it work on Linux at all perhaps, and I'm operating under a false assumption that this was running on dev and worked?

**Comment by steinnes** [comment]
screenshot from my linux machine:
![image](https://cloud.githubusercontent.com/assets/1097582/17894275/5ba1eb74-6938-11e6-88d0-d08a2e084b88.png)

Although I am not using it physically, so this might be some unicode magic happening in my iTerm2 and Python on Linux has no idea this is an emoji :-P

**Comment by ikornaselur** [comment]
The current version in use by us (itp v2.0.4) is using a library ([carpedm20/emoji](https://github.com/carpedm20/emoji)) which provides a regex [like this](https://github.com/carpedm20/emoji/blob/7809cd16f3f250da460ce261a2980c16906dd3ee/emoji/core.py#L74).

This worked fine, except that it's not catching "special" emojis, like the ❤️ - which is an old black heart plus a modifier (together a "surrogate pair", it was only returning the first part of the pair, which is ❤︎). That was the original reason for revisiting the emoji parsing in `instagram-text-python`, though it's turning out to be much more complicated than anticipated 😅

**Comment by ikornaselur** [comment]
> Although I am not using it physically, so this might be some unicode magic happening in my iTerm2 and Python on Linux has no idea this is an emoji :-P

I think it's just iterm2 magic 😋  I see emojis locally, but remotely it's the same as in your screenshot:

![image](https://cloud.githubusercontent.com/assets/3537289/17894398/c1013556-6938-11e6-8e54-d99669721a4c.png)

**Comment by ikornaselur** [comment]
Hm, I guess it might just be a bug (maybe intended) with the emoji library. They define the heart as `u':heart:': u'\U00002764',`, which is just the heavy black heart part. Both wide and narrow versions of python have the red heart as the surrogate pair:

![image](https://cloud.githubusercontent.com/assets/3537289/17894813/44da074e-693a-11e6-98be-704b69e9d00d.png)

(Wide at the top, narrow at the bottom)

**Comment by ikornaselur** [comment]
Closing as I'm removing the emoji parsing from this library.

Our emoji parsing will be handled with [TakumiHQ/emoji-unicode](https://github.com/TakumiHQ/emoji-unicode), which supports wide unicode python robustly and will support narrow partially (hopefully completely at some point)
